version: "1.0"
services:
  frontend:
    build:
      context: review-rocket-client
      target: development
    ports:
      - 80:80
    volumes:
      - ./review-rocket-client/src:/code/src
      - /code/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      args:
        - NODE_ENV=development
      context: review-rocket-server
      target: development
    command: npm start
    env_file: "./review-rocket-server/.env"
    environment:
      - NODE_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./review-rocket-server/src:/code/src:ro
      - ./review-rocket-server/package.json:/code/package.json
      - ./review-rocket-server/package-lock.json:/code/package-lock.json
