version: "1.0"
services:
  frontend:
    build:
      context: review-rocket-client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  backend:
    build:
      context: review-rocket-server
    command: npm start
    env_file: "./review-rocket-server/.env"
    ports:
      - 4000:4000
